# Site settings
title:          "플래닛조에"
description:    "미대출신 와인마케터의 데이터사이언티스트 전향의 기록"
url:            "https://zoeslee.github.io"

# Google Analytics
google_analytics: UA—XXXXXXXX-X

# Author
author:
  name:         Zoe Soohyun Lee
  url:          https://zoeslee.github.io
  email:        soohyunlee08@gmail.com

# Build settings
markdown:       kramdown
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed
  
google_fonts: "Nanum+Gothic:400,700"

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5

# Excludes
exclude: [ Gemfile, Gemfile.lock, tale.gemspec ]

# Disqus (Set to your disqus id)
disqus:         jekyll-tale
